### ISSUE TITLE
Question about dataset (gdf files) or EEG data provided by EE C247 class

### ISSUE THREAD

**Issue by AeronZhang** [krishk97/ECE-C247-EEG-GAN#4]
Hello, I am confused about how to process the .gdf files and get the .npy files (like the X_test.npy y_test.npy person_train_valid.npy).
With posted "# Function to EEG data, provided by EE C247 class" in load_data.py , could you share the (sample) of data you used? or would you like to share some code about processing those .gdf files? Thanks a lot!

**Comment by krishk97** [comment]
Hi @AeronZhang -- sorry for the late reply. Unfortunately, I cannot provide the data we used for the class as it goes against the guidelines students agreed to during the course. The course instructor only provided the .npy files, and did not share their preprocessing files. You could either contact the course instructor (Prof. Jonathan Kao at UCLA), or the original distributers of the BCI dataset (see http://www.bbci.de/competition/iv/). Sorry!

**Comment by venkatesh-kulkarni** [comment]
Could you tell me how X_train and X_test data can be generated? More specifically, the shape of the training/validation data is (2115, 22, 1000, 1). I understand that 22 is the number of EEG channels and 1000 is the number of time points and 2115 is the number of trials. Can you tell among these 2115 trials, which trials (ie first x or last x) of every subject have been utilised?
