### ISSUE TITLE
gdf to npy conversion

### ISSUE THREAD

**Issue by nabi-hassan** [krishk97/ECE-C247-EEG-GAN#5]
Hello,
I say that your Load_Data.py uses X_Test.npy but when I downloaded the dataset I got gdf file format. Can you please share your npy data or can you help me convert my gdf file to npy.
Thank You.

**Comment by danamariellanes** [comment]
Hello! Have you solved this issue? Because I encountered this problem as well.

**Comment by krishk97** [comment]
Hi. Unfortunately, I cannot provide the data we used for the class as it goes against the guidelines students agreed to during the course. The course instructor only provided the .npy files, and did not share their preprocessing files. You can try either contacting the course instructor (Prof. Jonathan Kao at UCLA).
