### ISSUE TITLE
Authorization required to access the Data

### ISSUE THREAD

**Issue by Vision238** [krishk97/ECE-C247-EEG-GAN#8]
I tried to access the data using url given in CNN_classification.ipynb file but I can't access the data through that URL because I don't have the authorisation. Can you please make the data for you project public. It will be very helpful.

**Comment by krishk97** [comment]
Hi. Unfortunately, I cannot provide the data we used for the class as it goes against the guidelines students agreed to during the course. The course instructor only provided the .npy files, and did not share their preprocessing files. You could either contact the course instructor (Prof. Jonathan Kao at UCLA), or the original distributers of the BCI dataset (see http://www.bbci.de/competition/iv/). Sorry!
